- func/send_coin.py
If a negative value is specified, it will not be sent coin.
> added processing when coin_amount is negative

- lib/mixlib.py
* added "import os"
* The clear function uses "os module", but it has not been imported.
> Fixed the phenomenon that ImportError is thrown when calling the clear function

- lib/settings.py
* removed unexecuted a line
* prevented unexpected exception handling
* fixed the magic number
* Handling all exceptions can lead to unexpected glitches, for example, If an error occurs when moving the directory, the existing file will be deleted, when the implementation before the change
* Magic number may interfere with future development
> fixed some potential glitches and magic numbers

- lib/mixlib.py
* added processing to throw an exception when an unplanned variable is stored
* If the `mode` variable is None or an unplanned value, `input(None)` will be executed because `question_text` has been indicated to be None in advance
> added processing to throw an exception when an unplanned variable is stored

- cli.py
- config.py
- func/node_connection.py
- gui.py
- ledger/ledger_main.py
- lib/config_system.py
- lib/mixlib.py
- lib/settings_system.py
- node/node.py
- node/unl.py
- test/test_config.py
- test/test_node.py
- test/test_settings.py
- test/test_wallet.py
- wallet/wallet.py
#15 
Information and preliminary discourse about a switching process
Pickle is a simple but not useless model and these saves cannot be used in other languages.
Systems except ledger switched to json save method
> Switching from pickle to json in the save system | Phase 1

- func/send_coin.py
* added type conversion to support `int` type
* It may be a little convenient if the function can handle int type as well
> added type conversion to support int type

- ledger/ledger_main.py
* changed the indent to 4 spaces
* The indent was 8 spaces
> cleaned indent

- ledger/ledger_main.py
* added data to dump to sequence_number variable can also be saved
* I reverted the changes regarding ledger class
* I added sequence_number = 0 as an optional argument
* I have successfully saved and restored Account class
* I have confirmed that an error occurs when changing ledger class #19
This is a modification of this pull request
#19
> added functions to load and dump Account class with json

- lib/mixlib.py
* added to throw an exception when unexpected values are stored
* we can see more obvious an error
> added processing of unexpected values

- .github/workflows/main.yml
- blockchain/block/block_main.py
- lib/settings_system.py
- node/myownp2pn.py
- test/test_config.py
- test/test_node.py
- test/test_settings.py
- test/test_wallet.py
- Reasons
- Solution
Speeding up the development process, and solving some problems
Github actions added. Solutions suitable for the problems were coded
Added for github actions.
Fixed for github actions.
Some fixes for pending and validating transaction order.
If the consensus is started the transaction which is incoming transaction, is save to pending transaction and end of the consensus this transaction will add the validating list.
> Some Fixes and Aded the Github Actions

- blockchain/block/block_main.py
- Reasons
- Solution
Previous gui and cli updates
Added a thread based class for apps
> Added the Apps Threader

- blockchain/block/transaction.py
This function gets for the hash value of sha256, but if we use any other hash algorithm I plan to apply that change and rebase
> added a function to check the hash value of sha256 of transaction class

- blockchain/block/block_main.py
- func/send.py
- node/myownp2pn.py
- node/unl.py
Some errors in networks with more than 2 nodes in the consensus process.
Problems on the catching up to the network.
Problematic events in the approval and disapproval of transactions.
...
Solution model developed and implemented.
> Fix pack for consensus

- .gitignore
- blockchain/block/block_main.py
- config.py
- node/myownp2pn.py
- Not saving validated blocks
- Consensus structure is not applied correctly in some areas
- A database was created with the sqllite 3 library
- Consensus structure corrected
> Saving Blocks to SQLite Database and Some Fixes Added

- blockchain/block/account.py
* added a function named `get_hash`
* I think this function is useful for implementing the block chain.
> added a function to get the hash value of hash256 of an instance of Account class

- test/test_config.py
- test/test_node.py
- test/test_settings.py
* I removed the blank line at the end of the file in the test directory
> removed trailing blank line

- blockchain/block/account.py
- Some incompatible codes from old versions
- The necessary solution has been applied. (Some deletions and word corrections)
> Small fixes for Account Class

- blockchain/block/block_main.py
- Performance and stability problems.
- The timings were rearranged, the block time was adjusted with a fixed formula.
> Performance Optimization for Block Times

- src/accounts/account.py
* fixed E302
* fixed E501
* This is a good way to improve coding quality.
> fixed several pep8 violation in account.py

- src/accounts/account.py
- src/accounts/get_balance.py
- src/accounts/get_sequance_number.py
- src/app/app_main.py
- src/blockchain/block/block_main.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/create_block.py
- src/blockchain/block/get_block.py
- src/blockchain/block/save_block_to_blockchain_db.py
- src/cli.py
- src/consensus/consensus_first_round.py
- src/consensus/consensus_main.py
- src/gui_lib/libs/baseclass/node_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/node/get_node_list.py
- src/node/myownp2pn.py
- src/transactions/pending_to_validating.py
- src/transactions/process_the_transaction.py
- src/transactions/send.py
- This is a good way to improve coding quality.
- Problem on new account creation (too many same account)
- Various improvements have been made
- The part that created the new user has been moved to the upper loop
> Code Quality Improvements and Fix for New Account Creation

- src/blockchain/block/block_main.py
- src/blockchain/block/create_block.py
- src/blockchain/candidate_block/candidate_block_main.py
- src/blockchain/candidate_block/get_candidate_blocks.py
- src/cli.py
- src/consensus/consensus_first_round.py
- src/consensus/consensus_second_round.py
- src/gui_lib/libs/baseclass/node_screen.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/lib/mixlib.py
- src/node/myownp2pn.py
- src/node/node.py
- This is a good way to improve coding quality.
- Problem on unl nodes. (Unl nodes added later are not included in the consensus process)
- Various improvements have been made
- self.total_validators is removed and added the get_unl_nodes()
> code quality improvements and unl nodes fixes

- src/accounts/account.py
- src/accounts/get_balance.py
- src/accounts/get_sequance_number.py
- src/blockchain/block/block_main.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/create_block.py
- src/blockchain/block/save_block_to_blockchain_db.py
- src/transactions/process_the_transaction.py
- src/transactions/transaction.py
- src/wallet/wallet.py
#54 
Old size: MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEAtLa9K8MLg+frIEFBYmbYDsc0INqXedAF8SlpEGQQmOSjKV+6MxpVP53bl6elalJfCMV33WhqAelf3qkx+QHvw==
New Size:
b4156987a4b97ac4ad052262652786dc513d1746
> Account PublicKey Size Improvements (Added Address System)

- src/blockchain/block/block_main.py
- src/cli.py
- src/gui_lib/libs/baseclass/operations_screen.py
> Added The Minumum Transfer Amount

- src/blockchain/block/block_main.py
- src/blockchain/block/calculate_hash.py
- src/node/myownp2pn.py
- src/transactions/send.py
* #64
* This will be effective in resolving the issue
I wrote this mechanism with almost no changes to the existing implementation.
I used the function annotation for clarity, but it's different from the existing writing style, so I'll change it if you care about this.
>  added a mechanism to change transaction fee

- src/accounts/get_balance.py
> Added Reserve Control Mechanism

- src/accounts/get_balance.py
- src/blockchain/block/block_main.py
- src/consensus/consensus_main.py
- src/consensus/consensus_second_round.py
- src/node/myownp2pn.py
> Block time Adjustment Mechanism

- .gitignore
- src/blockchain/block/block_main.py
- src/blockchain/block/blocks_hash.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/create_block.py
- src/config.py
- src/lib/merkle_root.py
- src/node/myownp2pn.py
> Added new blocks hash list system

- README.md
- doc/release-notes/release-notes-0.2.0-alpha.md
- requirements.txt
- src/blockchain/block/create_block.py
- src/cli.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/gui_lib/libs/kv/operations_screen.kv
- src/gui_lib/libs/kv/wallet_screen.kv
- src/lib/settings_system.py
- src/transactions/send_coin.py
- src/wallet/wallet.py
https://github.com/onuratakan/Decentra-Network/blob/0.2.0-alpha/doc/release-notes/release-notes-0.2.0-alpha.md
> 0.2.0 alpha

- src/cli.py
Long time no see.
I'm glad to see you again.
I omitted unnecessary calculations.
This is the same result as before the change.
> Removed useless calculations

- .gitignore
- doc/release-notes/release-notes-0.3.0-alpha.md
- src/blockchain/block/save_block_to_blockchain_db.py
- src/cli.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/gui_lib/libs/kv/operations_screen.kv
- src/gui_lib/libs/kv/wallet_screen.kv
- src/lib/encryption.py
- src/lib/settings_system.py
- src/transactions/send.py
- src/transactions/send_coin.py
- src/wallet/wallet.py
- test/test_node.py
- test/test_wallet.py
https://github.com/onuratakan/Decentra-Network/blob/0.3.0-alpha/doc/release-notes/release-notes-0.3.0-alpha.md
> 0.3.0 alpha

- README.md
- doc/release-notes/release-notes-0.3.1-alpha.md
- requirements.txt
- src/gui.py
- src/gui_lib/libs/baseclass/node_screen.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/gui_lib/libs/kv/node_screen.kv
- src/gui_lib/libs/kv/operations_screen.kv
- src/gui_lib/libs/kv/settings_screen.kv
- src/gui_lib/libs/kv/wallet_screen.kv
- src/gui_lib/libs/kv/welcome_screen.kv
https://github.com/onuratakan/Decentra-Network/blob/0.3.1-alpha/doc/release-notes/release-notes-0.3.1-alpha.md
#139
#138
> 0.3.1 alpha

- doc/release-notes/release-notes-0.4.0-alpha.md
- src/cli.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/gui_lib/libs/kv/wallet_screen.kv
- src/lib/settings_system.py
- src/wallet/wallet.py
https://github.com/onuratakan/Decentra-Network/blob/0.4.0-alpha/doc/release-notes/release-notes-0.4.0-alpha.md
> 0.4.0 alpha

- README.md
- doc/release-notes/release-notes-0.4.2-alpha.md
- src/blockchain/block/block_main.py
https://github.com/onuratakan/Decentra-Network/blob/0.4.2-alpha/doc/release-notes/release-notes-0.4.2-alpha.md
> 0.4.2 alpha

- .gitignore
- README.md
- doc/release-notes/release-notes-0.4.3-alpha.md
- src/accounts/account.py
- src/blockchain/block/block_main.py
- src/blockchain/block/blocks_hash.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/save_block_to_blockchain_db.py
- src/config.py
- src/transactions/process_the_transaction.py
https://github.com/onuratakan/Decentra-Network/blob/0.4.3-alpha/doc/release-notes/release-notes-0.4.3-alpha.md
> 0.4.3 alpha

- README.md
- doc/release-notes/release-notes-0.4.4-alpha.md
- src/blockchain/block/block_main.py
- src/blockchain/block/calculate_hash.py
- src/transactions/process_the_transaction.py
https://github.com/onuratakan/Decentra-Network/blob/0.4.4-alpha/doc/release-notes/release-notes-0.4.4-alpha.md
> 0.4.4 alpha

- functional_test/docker/docker.py
- functional_test/local/local.py
- src/api.py
- src/app/app_main.py
- src/blockchain/block/save_block_to_blockchain_db.py
- src/cli.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/gui_lib/libs/baseclass/wallet_screen.py
- src/lib/mixlib.py
- src/node/myownp2pn.py
- src/node/unl.py
- src/wallet/create_a_wallet.py
- src/wallet/print_wallets.py
- src/wallet/wallet.py
- src/wallet/wallet_selector.py
Code quality has been improved.
> Code Quality Improvements

- src/transactions/send_the_coin.py
Removed multiple conversions of the same type and unnecessary conditional branches.
* fixed E772
* removed unnecessary conditional branches
* removed multiple conversions of the same type
> improved code quality and speed

- setups/api/setup.py
- setups/gui/setup.py
> setups: Added main package to api and gui packages

- setup.py
- setups/api/setup.py
- setups/gui/setup.py
> Adding the licence to all files

- src/blockchain/block/calculate_hash.py
> A fixed for calculation the hash

- src/accounts/account.py
- src/accounts/get_accounts.py
- src/accounts/get_accounts_part.py
- src/accounts/get_balance.py
- src/accounts/get_sequance_number.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/save_block_to_blockchain_db.py
> Seperation for get accounts functions

- src/accounts/get_accounts.py
- src/accounts/get_accounts_part.py
> Docstring for get accounts functions

- src/blockchain/block/block_main.py
> Backup the blockchain

- src/blockchain/block/block_main.py
- src/blockchain/block/create_block.py
> Added restore previous hash from currently block at TEMP_BLOCK_PATH

- API.spec
- CLI.spec
- GUI.spec
> Adding the spec files for exe

- README.md
> Added codebeat badge

- README.md
> Added codescene badges

- README.md
> Added repography dashboards

- auto_builders/docker.py
- auto_builders/local.py
> Fix for auto builders parameter help messages

- .github/workflows/functional_tests.yml
> Added auto builders folders to functional test workflow

- docs/getting-started/downloading.md
> Changed the dowload description of api and gui exe

- auto_builders/docker.py
- auto_builders/local.py
> Code quality improvements for auto builders

- .github/workflows/upload_python_package.yml
> GitHub workflow for the pypi package build and publish

- docs/getting-started/downloading.md
- docs/getting-started/using.md
> Removed the exe instructions from downloading and using

- docs/release-notes/release-notes-0.13.0-alpha.md
- requirements/api.txt
- requirements/gui.txt
- setup.py
- setups/api/setup.py
- setups/gui/setup.py
> Added version 0.13.0

- src/blockchain/block/block_main.py
> Code Quality Improvements for src/blockchain/block/block_main.py

- src/consensus/consensus_first_round.py
> Code Quality improvements for src/consensus/consensus_first_round.py

- functional_test/docker/test_decentra_network_docker.py
> Performing functional tests according to success as a result of multiple trials

- src/consensus/consensus_first_round.py
- src/consensus/consensus_main.py
- src/consensus/consensus_second_round.py
> Code Quality Imorovements for src/consensus

- test/test_api.py
> unit_test: Added API Unit test

- docs/release-notes/release-notes-0.14.0-alpha.md
- requirements/api.txt
- requirements/gui.txt
- setup.py
- setups/api/setup.py
- setups/gui/setup.py
> Issue 339 releasing 0.14.0-alpha version

- src/app/app_main.py
- src/blockchain/block/block_main.py
- src/node/node.py
> Removed the apps_starter and app class

- .github/workflows/deploys.yml
- .github/workflows/tests.yml
- requirements/api.txt
- requirements/gui.txt
- setup.py
- setups/api/setup.py
- setups/gui/setup.py
> 363 removing the main package from api and gui packege requirements

- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yml
- docs/systems/function_test.md
- tests/functional_tests/docker/test_decentra_network_docker.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_config.py
- tests/unit_tests/test_node.py
- tests/unit_tests/test_settings.py
- tests/unit_tests/test_wallet.py
> 359 rename and moving for testunit test and functional test

- src/blockchain/block/block_main.py
> block: Added green paper hash

- .github/workflows/tests.yml
- tests/functional_tests/local/test_decentra_network_local.py
> 370 moving to the local based functional tests

- .gitignore
- src/api.py
- src/app/app_main.py
- src/blockchain/block/block_main.py
- src/blockchain/block/calculate_hash.py
- src/blockchain/block/create_block.py
- src/cli.py
- src/config.py
- src/consensus/consensus_first_round.py
- src/consensus/consensus_main.py
- src/consensus/consensus_second_round.py
- src/gui.py
- src/lib/log.py
- src/lib/mixlib.py
- src/logs/README.md
- src/node/node.py
- src/node/node_connection.py
- src/transactions/check_transaction.py
- src/transactions/pending_to_validating.py
- src/transactions/send_transaction_to_the_block.py
> 349 adding log system

- .github/workflows/tests.yml
> 372 adding log files as artifacts to the actions

- .github/workflows/dependency-review.yml
- .github/workflows/devskim.yml
- .github/workflows/fortify.yml
- .github/workflows/ossar.yml
- .github/workflows/sysdig-scan.yml
> 379 adding security scanner workflows

- auto_builders/docker.py
- auto_builders/local.py
> Added some time sleeps

- README.md
> readme: Added PyPI dowloads

- auto_builders/docker.py
- auto_builders/local.py
- docs/systems/api.md
- tests/functional_tests/local/test_decentra_network_local.py
> Changed the port range for api and node

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
- auto_builders/local.py
- functional_test/local/test_decentra_network_local_10_3.py
- functional_test/local/test_decentra_network_local_3_1.py
- functional_test/local/test_decentra_network_local_4_1.py
- functional_test/local/test_decentra_network_local_5_1.py
- functional_test/local/test_decentra_network_local_5_2.py
- functional_test/local/test_decentra_network_local_6_1.py
- functional_test/local/test_decentra_network_local_6_2.py
- functional_test/local/test_decentra_network_local_7_1.py
- functional_test/local/test_decentra_network_local_7_2.py
> tests: Added local based stabilty tests

- .github/release.yml
- auto_builders/docker.py
- auto_builders/local.py
- src/lib/settings_system.py
> logger: Fixed auto builders installation bug with changing default settings value of debug mode

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
> actions: Added workflow_run to stability tests

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
> actions: Changed the getting way to local build for docker image

- .gitignore
- auto_builders/local.py
> auto_builders: Local based .out file set differently for each node

- setups/api/setup.py
> setups: Synced the requirements with api setup.py

- src/cli.py
- src/gui.py
> Removed loguru library

- src/transactions/process_the_transaction.py
> transactions: Changed the order mechanism

- src/transactions/process_the_transaction.py
> transaction: Added a new list to proccess the transaction function for sacalability in big lists

- src/wallet/wallet.py
> wallet: Added a transform process to Address function

- src/accounts/get_balance.py
- src/accounts/get_sequance_number.py
- src/transactions/check_transaction.py
- src/transactions/send.py
- src/transactions/send_transaction_to_the_block.py
> transactions: Disabled multiple transactions from the same account in one block

- auto_builders/docker.py
- auto_builders/local.py
- src/blockchain/block/block_main.py
- src/lib/status.py
- tests/stability_tests/docker/test_decentra_network_docker_10_3.py
- tests/stability_tests/docker/test_decentra_network_docker_3_1.py
- tests/stability_tests/docker/test_decentra_network_docker_4_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_2.py
- tests/stability_tests/docker/test_decentra_network_docker_6_1.py
- tests/stability_tests/docker/test_decentra_network_docker_6_2.py
- tests/stability_tests/docker/test_decentra_network_docker_7_1.py
- tests/stability_tests/docker/test_decentra_network_docker_7_2.py
- tests/stability_tests/local/test_decentra_network_local_10_3.py
- tests/stability_tests/local/test_decentra_network_local_3_1.py
- tests/stability_tests/local/test_decentra_network_local_4_1.py
- tests/stability_tests/local/test_decentra_network_local_5_1.py
- tests/stability_tests/local/test_decentra_network_local_5_2.py
- tests/stability_tests/local/test_decentra_network_local_6_1.py
- tests/stability_tests/local/test_decentra_network_local_6_2.py
- tests/stability_tests/local/test_decentra_network_local_7_1.py
- tests/stability_tests/local/test_decentra_network_local_7_2.py
> block: Block time increased

- src/blockchain/candidate_block/get_candidate_blocks.py
- src/node/node.py
> node: Added a check point for taken candidate block and hash

- src/lib/status.py
> status: Removed time difference based status value

- src/blockchain/block/block_main.py
- src/consensus/consensus_first_round.py
- src/consensus/consensus_main.py
- src/consensus/consensus_second_round.py
> block: Removed unused elements

- tests/functional_tests/local/test_decentra_network_local.py
> tests: Increased the functional tests time sleeps for new block time

- tests/functional_tests/local/test_decentra_network_local.py
> tests: Optimized and fixed functional tests

- .github/workflows/gource.yml
> github: Added Gource actions

- auto_builders/docker.py
- auto_builders/local.py
> auto_builders: Added randomly connect circle node to another circle node

- src/blockchain/block/block_main.py
> block: Removed the gap

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
> github: Added workflow_dispatch to stability tests

- src/node/node.py
> node: Removed check point that control taken candidate block and block hash

- src/blockchain/block/block_main.py
> block: Removed gap of block time

- .github/workflows/gource.yml
> github: Some settings are set for Gource Action

- src/blockchain/block/block_main.py
> block: Added new version of Green Paper as sha256

- README.md
> docs: Changed the docs site link in README.md

- .github/release.yml
- .github/workflows/builds.yml
- README.md
> github: Changed build to builds

- src/api.py
- src/cli.py
- src/gui.py
- src/lib/safety.py
> security: Added pywall library based safety check process

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
> github: Changed Deploy workflow run trigger to release publish trigger for stability tests

- .github/release.yml
Closes #534 
Closes #535 
Closes #536 
Closes #537
> github: Fixed tralling space issues in release.yml

- docker/github/api/Dockerfile
- docker/local/api/Dockerfile
Closes #530 
Closes #529 
Closes #532 
Closes #533
> docker: Code quality improvements for api dockerfiles

- docker/github/cli/Dockerfile
- docker/local/cli/Dockerfile
> docker: Fixed code quality issues of cli dockerfiles

- .github/workflows/tests.yml
- setup.py
- setups/api/setup.py
- setups/gui/setup.py
> setup-setups-github: Changed required python version with at leas 3.8

- .github/workflows/deploys.yml
> github: Added Deploy environment to Deploy workflow

- src/transactions/send_transaction_to_the_block.py
> transactions: Removed the print function of send_transaction_to_the_block

- tests/functional_tests/local/test_decentra_network_local.py
- tests/stability_tests/docker/test_decentra_network_docker_10_3.py
- tests/stability_tests/docker/test_decentra_network_docker_3_1.py
- tests/stability_tests/docker/test_decentra_network_docker_4_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_2.py
- tests/stability_tests/docker/test_decentra_network_docker_6_1.py
- tests/stability_tests/docker/test_decentra_network_docker_6_2.py
- tests/stability_tests/docker/test_decentra_network_docker_7_1.py
- tests/stability_tests/docker/test_decentra_network_docker_7_2.py
- tests/stability_tests/local/test_decentra_network_local_10_3.py
- tests/stability_tests/local/test_decentra_network_local_3_1.py
- tests/stability_tests/local/test_decentra_network_local_4_1.py
- tests/stability_tests/local/test_decentra_network_local_5_1.py
- tests/stability_tests/local/test_decentra_network_local_5_2.py
- tests/stability_tests/local/test_decentra_network_local_6_1.py
- tests/stability_tests/local/test_decentra_network_local_6_2.py
- tests/stability_tests/local/test_decentra_network_local_7_1.py
- tests/stability_tests/local/test_decentra_network_local_7_2.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_config.py
- tests/unit_tests/test_node.py
- tests/unit_tests/test_settings.py
- tests/unit_tests/test_wallet.py
> tests: Changed th test names

- .github/workflows/tests.yml
- tests/functional_tests/docker/test_decentra_network_docker.py
> tests: Added docker based functional test

- .github/workflows/tests.yml
> github: Added status information to functional tests

- src/blockchain/block/block_main.py
> block: Added validating time reset in block reset

- src/blockchain/block/block_main.py
> block: Added a space from consensus process and block time

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
> github: Added Status Information to stability tests

- .github/workflows/tests.yml
- auto_builders/docker.py
- docs/getting-started/using.md
> github: Added log as artifacts for docker based functional test job

- src/node/node.py
> node: Added send full accounts and blocks hash to send full chain

- src/api.py
- src/blockchain/block/block_main.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/lib/export.py
- src/lib/status.py
- src/transactions/print_transactions.py
- src/transactions/save_my_transaction.py
- src/transactions/save_to_my_transaction.py
- src/transactions/validate_transaction.py
- src/wallet/save_wallet_list.py
> transactions: Added approved and unapproved type as true to my transaction

- .github/workflows/deploys.yml
> github: Changed Deploy environment name to Deploys

- .github/workflows/builds.yml
- .github/workflows/gource.yml
> github: Added Builds environment

- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/devskim.yml
- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
- .github/workflows/ossar.yml
- .github/workflows/tests.yml
> github: Added Tests environment

- src/transactions/check_transaction.py
- src/transactions/send.py
> transaction: Amount and fee decimal amount limited to block.transaction_fee

- .github/workflows/builds.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/tests.yml
> github: Removed after workflow run Tests triggers

- docs/getting-started/downloading.md
- docs/getting-started/using.md
> docs: Added new dowload links and using docs

- docs/apps/embedded/definition_for_app.md
> docs: Added document for application developer that closing the thread after succeed works

- src/transactions/check_transaction.py
- src/transactions/send_transaction_to_the_block.py
> transaction: Set limits for fromUser and toUser and added type checking for transaction elements

- src/transactions/check_transaction.py
- src/transactions/send.py
> transaction: Limit set for len of data

- .github/workflows/gource.yml
> github: Changed the name and job name of gource.yml

- src/lib/settings_system.py
- src/wallet/wallet_selector.py
- tests/unit_tests/test_wallet.py
> tests: Added unit tests for wallet_selector function

- src/wallet/delete_current_wallet.py
- src/wallet/wallet_delete.py
- tests/unit_tests/test_wallet.py
> tests: Added unit tests for delete_current_wallet function

- tests/unit_tests/test_transactions.py
Closes #618
Closes #619
Closes #620
Closes #621
> tests: Adding unit test for my transaction functions

- tests/unit_tests/test_transactions.py
> tests: Added unit tests for dumb and load json transaction

- tests/unit_tests/test_wallet.py
> tests: Added unit test for print_wallets function if not current_wallet == number situation

- tests/unit_tests/test_wallet.py
> tests: Added unit test for wallet_import function if not -1 == account else situation

- src/wallet/wallet_import.py
- tests/unit_tests/test_wallet.py
> tests: Added unit test for wallet_import if not password is None and not list(temp_saved_wallet).index(account) == 0 else situation

- tests/unit_tests/test_wallet.py
> tests: Adding unit test for wallet_import mode == 2 situation

- src/blockchain/block/block_main.py
- src/blockchain/block/create_block.py
- src/transactions/pending_to_validating.py
- tests/unit_tests/test_transactions.py
> tests: Added unit test for PendinttoValidating function and changed with PendingtoValidating and fixed the block previous hash

- src/blockchain/block/block_main.py
- src/transactions/check_transaction.py
- tests/unit_tests/test_transactions.py
> tests: Added unit tests for ChangeTransactionFee function

- src/accounts/account.py
- src/blockchain/block/block_main.py
- tests/functional_tests/docker/test_decentra_network_docker.py
- tests/functional_tests/local/test_decentra_network_local.py
- tests/stability_tests/docker/test_decentra_network_docker_10_3.py
- tests/stability_tests/docker/test_decentra_network_docker_3_1.py
- tests/stability_tests/docker/test_decentra_network_docker_4_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_2.py
- tests/stability_tests/docker/test_decentra_network_docker_6_1.py
- tests/stability_tests/docker/test_decentra_network_docker_6_2.py
- tests/stability_tests/docker/test_decentra_network_docker_7_1.py
- tests/stability_tests/docker/test_decentra_network_docker_7_2.py
- tests/stability_tests/local/test_decentra_network_local_10_3.py
- tests/stability_tests/local/test_decentra_network_local_3_1.py
- tests/stability_tests/local/test_decentra_network_local_4_1.py
- tests/stability_tests/local/test_decentra_network_local_5_1.py
- tests/stability_tests/local/test_decentra_network_local_5_2.py
- tests/stability_tests/local/test_decentra_network_local_6_1.py
- tests/stability_tests/local/test_decentra_network_local_6_2.py
- tests/stability_tests/local/test_decentra_network_local_7_1.py
- tests/stability_tests/local/test_decentra_network_local_7_2.py
- tests/unit_tests/test_accounts.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_config.py
- tests/unit_tests/test_node.py
- tests/unit_tests/test_settings.py
- tests/unit_tests/test_transactions.py
- tests/unit_tests/test_wallet.py
> tests: Added unit test for account class and removed test numbers

- .github/release.yml
> github: Changed cli menu and paremeters label to CLI

- .gitignore
- src/api.py
- src/blockchain/block/block_main.py
- src/blockchain/block/blocks_hash.py
- src/blockchain/block/create_block.py
- src/blockchain/block/get_block.py
- src/blockchain/block/save_block.py
- src/cli.py
- src/consensus/consensus_first_round.py
- src/consensus/consensus_main.py
- src/consensus/consensus_second_round.py
- src/gui_lib/libs/baseclass/operations_screen.py
- src/node/node.py
- tests/unit_tests/test_blockchain.py
> tests: Added unit tests for SaveBlock and GetBlock functions

- src/blockchain/candidate_block/get_candidate_blocks.py
- tests/unit_tests/test_blockchain.py
> tests: Added unit test for candidate_block and GetCandidateBlocks functions

- src/blockchain/block/get_block_from_blockchain_db.py
- src/blockchain/block/save_block_to_blockchain_db.py
- src/consensus/consensus_main.py
- src/db/test_SaveBlockstoBlockchainDB_GetBlockstoBlockchainDB/README.md
- src/db/test_SaveBlockstoBlockchainDB_GetBlockstoBlockchainDB_not_our_transaction/README.md
- src/lib/log.py
- tests/unit_tests/test_blockchain.py
> tests: Added unit test for SaveBlockstoBlockchainDB and GetBlockstoBlockchainDB function

- .github/workflows/codecov.yml
- .github/workflows/tests.yml
- auto_builders/docker.py
- auto_builders/local.py
- tests/functional_tests/docker/test_decentra_network_docker.py
- tests/functional_tests/local/test_decentra_network_local.py
- tests/stability_tests/docker/test_decentra_network_docker_10_3.py
- tests/stability_tests/docker/test_decentra_network_docker_3_1.py
- tests/stability_tests/docker/test_decentra_network_docker_4_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_2.py
- tests/stability_tests/docker/test_decentra_network_docker_6_1.py
- tests/stability_tests/docker/test_decentra_network_docker_6_2.py
- tests/stability_tests/docker/test_decentra_network_docker_7_1.py
- tests/stability_tests/docker/test_decentra_network_docker_7_2.py
- tests/stability_tests/local/test_decentra_network_local_10_3.py
- tests/stability_tests/local/test_decentra_network_local_3_1.py
- tests/stability_tests/local/test_decentra_network_local_4_1.py
- tests/stability_tests/local/test_decentra_network_local_5_1.py
- tests/stability_tests/local/test_decentra_network_local_5_2.py
- tests/stability_tests/local/test_decentra_network_local_6_1.py
- tests/stability_tests/local/test_decentra_network_local_6_2.py
- tests/stability_tests/local/test_decentra_network_local_7_1.py
- tests/stability_tests/local/test_decentra_network_local_7_2.py
> auto_builders: Decreased the sleep time after build

- tests/unit_tests/test_blockchain.py
> tests: Added unit test fpr dump and load json functions of Block class

- auto_builders/docker.py
- auto_builders/local.py
- src/api.py
- src/cli.py
- src/gui.py
- src/lib/config_system.py
- src/lib/export.py
- src/lib/merkle_root.py
- src/lib/mixlib.py
- src/lib/safety.py
- src/lib/settings_system.py
- src/lib/status.py
- src/node/node.py
- src/node/unl.py
- src/transactions/check/datas/check_datas.py
- src/transactions/check/len/check_len.py
- src/transactions/my_transactions/save_my_transaction.py
- src/transactions/print_transactions.py
- src/transactions/send.py
- src/wallet/delete_current_wallet.py
- src/wallet/ellipticcurve/math.py
- src/wallet/ellipticcurve/publicKey.py
- src/wallet/print_wallets.py
- src/wallet/wallet_create.py
- src/wallet/wallet_import.py
- src/wallet/wallet_selector.py
🕊 Some Refactorings For Clean Code
> Some Refactorings For Clean Code

- src/node/node.py
> node: Deleted disconnect_to_node function of Node class

- src/node/node.py
Reverts Decentra-Network/Decentra-Network#782
> Revert "node: Deleted disconnect_to_node function of Node class"

- tests/unit_tests/test_node.py
> tests: Added unit tests for parse_packet function of Connection class

- tests/unit_tests/test_wallet.py
> tests: Added unit test for Address function

- src/node/connection.py
- src/node/node.py
- tests/unit_tests/test_node.py
> tests: Added unit tests for if not Unl.node_is_unl(connected_node_id) situation of run and connect_to_node functions of Node class

- decentra_network/gui.py
- decentra_network/gui_lib/libs/kv/root_screen.kv
- setup.py
package_dir removed from setup.py for causing this;
```bash
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
running egg_info
creating /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info
writing /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/PKG-INFO
writing dependency_links to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/dependency_links.txt
writing entry points to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/entry_points.txt
writing top-level names to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/top_level.txt
writing manifest file '/tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/SOURCES.txt'
error: package …
```
> setup and gui: minor improvements

- tests/unit_tests/test_node.py
> tests: Merged all node unit tests that start and close Node and Connection in one test

- auto_builders/docker.py
- auto_builders/local.py
- decentra_network/node/client/client.py
- decentra_network/node/server/server.py
- decentra_network/node/unl.py
- tests/unit_tests/test_node.py
> node: Added a forwadder for send function to send_client

- decentra_network/api.py
- decentra_network/cli.py
- decentra_network/gui_lib/libs/baseclass/node_screen.py
- decentra_network/lib/perpetualtimer.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_node.py
> tests: Added unit test for send_full_chain get_full_chain functions of server

- decentra_network/node/server/server.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_node.py
> tests: Added unit tests for send full accounts and get full accounts functions

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> test: Added unit tests for send_full_blockcshash get_full_blockshash functions of server

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> tests: Added unit tests for false messages types of server system

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> tests: Added unit test for socket.timeout situation of server.connect function

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> node: Removed not exist situation of get_connected_nodes function of server

- decentra_network/db/connected_nodes_test_0/README.md
- decentra_network/db/connected_nodes_test_1/README.md
- decentra_network/db/connected_nodes_test_2/README.md
- decentra_network/lib/clean_up.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> tests: Added test_connectionfrommixdb and test_connected_node_delete_and_save in test_node

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> tests: Added unit tests for send_block_to_other_nodes and send_me_full_block function

- tests/unit_tests/test_node.py
> tests: Added unit tests for send_my_block and get_candidate_block functions of server

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> tests: Added unit test for send and get candidate block hash

- decentra_network/node/unl.py
- tests/unit_tests/test_node.py
> tests: Added unit test for os path not exist situation of get_unl_nodes

- tests/unit_tests/test_wallet.py
> tests: Added unit test for not in list wallet number situation of wallet_import

- tests/unit_tests/test_node.py
> tests: Decreased time sleeps for node system testing

- decentra_network/consensus/consensus_main.py
- decentra_network/db/pending_transactions_test_3/README.md
- decentra_network/db/pending_transactions_test_4/README.md
- decentra_network/db/pending_transactions_test_5/README.md
- decentra_network/lib/clean_up.py
- decentra_network/transactions/get_transaction.py
- decentra_network/transactions/pending_to_validating.py
- tests/unit_tests/test_transactions.py
> transactions: Changed PendingtoValidating function approach

- auto_builders/docker.py
- auto_builders/local.py
> auto_builders: Decreased sleep times

- .github/release.yml
> github: Changed Documatation label to Docs

- .github/workflows/gource.yml
- README.md
- docs/getting-started/using.md
- setups/api/setup.py
- setups/gui/setup.py
> docs: Removed "Core" name

- .github/pull_request_template.md
> github: Added pull request template

- README.md
> docs: Added cloudback.it to README.md

- README.md
> docs: Added deploys workflow badge to README.md

- .github/workflows/builds.yml
- .github/workflows/gource.yml
> github: Added automatic upload the artifacts system

- .github/workflows/builds.yml
- .github/workflows/gource.yml
For fixing the previously system.
> Fix for automatic adding release asset

- .github/labeler.yml
- .github/release.yml
- .github/workflows/labeler.yml
> github: Added automatic labeler for pull requests

- .github/workflows/builds.yml
> github: Added caching for build android api and gui jobs

- .github/labeler.yml
- .github/workflows/devskim.yml
- .github/workflows/ossar.yml
> github: Disabled some triggers of devskrim and ossar workflows

- .github/workflows/dependency-review.yml
- .github/workflows/devskim.yml
- .github/workflows/ossar.yml
> github: Disabled some worflow triggers that run for document files

- .github/labeler.yml
- .github/workflows/labeler.yml
> github: Added automatic issue labeler

- .github/workflows/builds.yml
- .github/workflows/gource.yml
> github: Added name for jobs artifacts

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/hash/accounts_hash.py
- decentra_network/transactions/process_the_transaction.py
- tests/unit_tests/test_blockchain.py
> blockchain: Removed edited accounts value

- .github/workflows/tests.yml
Closes #940
Closes #941
Closes #942
> github: Added caching to tests workflow jobs

- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
> github: Added caching to stability tests

- .github/workflows/builds.yml
- .github/workflows/codecov.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/deploys.yml
- .github/workflows/devskim.yml
- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/gource.yml
- .github/workflows/labeler.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
- .github/workflows/ossar.yml
- .github/workflows/tests.yml
> github: Added concurrency for workflows

- .github/workflows/codecov.yml
> github: Added caching for codecov workflow

- .gitignore
- decentra_network/accounts/get_accounts.py
- decentra_network/accounts/get_balance.py
- decentra_network/accounts/get_sequance_number.py
- decentra_network/accounts/save_accounts.py
- decentra_network/blockchain/block/get_block_from_blockchain_db.py
- decentra_network/blockchain/block/save_block.py
- decentra_network/blockchain/block/save_block_to_blockchain_db.py
- decentra_network/config.py
- decentra_network/consensus/rounds/round_1/process/process_main.py
- decentra_network/lib/clean_up.py
- decentra_network/node/client/client.py
- decentra_network/node/server/server.py
- decentra_network/transactions/check/datas/check_datas.py
- decentra_network/transactions/process_the_transaction.py
- tests/unit_tests/test_accounts.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_node.py
- tests/unit_tests/test_transactions.py
> accounts: Used sqllite3 for account

- tests/unit_tests/test_consensus.py
> tests: Added unit test for transactions_main function

- decentra_network/blockchain/block/save_block_to_blockchain_db.py
- decentra_network/consensus/finished/finished_main.py
- decentra_network/db/test_finished_main/README.md
- decentra_network/db/test_finished_main_false_time/README.md
- decentra_network/db/test_finished_main_no_reset/README.md
- decentra_network/lib/clean_up.py
- decentra_network/transactions/my_transactions/get_my_transaction.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for finished_main function

- decentra_network/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for candidate_blocks_check function

- auto_builders/docker.py
- decentra_network/node/client/client.py
- decentra_network/node/server/server.py
> node: Added buffer adder for preventing errors

- decentra_network/blockchain/block/change_transaction_fee.py
- decentra_network/transactions/pending/get_pending.py
- tests/unit_tests/test_transactions.py
> transactions: Created a GetPendingAmount function for using in just len needed situation like ChangeTransactionFee

- decentra_network/transactions/pending/get_pending.py
- decentra_network/transactions/pending/remove_same_pending.py
- tests/unit_tests/test_transactions.py
> transactions: Added remove same pendings to get pendings functions

- tests/unit_tests/test_consensus.py
> tests: Added unit test for time_difference_check function of round 1

- tests/unit_tests/test_consensus.py
> tests: Added unit test for round_check function of round 1

- decentra_network/consensus/rounds/round_1/process/transactions/find_newly/find_newly_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for find_newly function

- tests/unit_tests/test_consensus.py
> tests: Added unit test for find_validated function

- decentra_network/consensus/rounds/round_1/process/transactions/transactions_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for transactions_main function of round 1

- decentra_network/consensus/rounds/round_1/process/process_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for round_process function of round 1

- tests/unit_tests/test_consensus.py
> tests: Added unit test for time_difference_check function of round 2

- tests/unit_tests/test_consensus.py
> tests: Added unit test for round_check function of round 2

- decentra_network/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for process_candidate_blocks_hashes function

- decentra_network/consensus/rounds/round_2/process/validate/validate_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for validate_main function

- decentra_network/consensus/rounds/round_2/process/process_main.py
- decentra_network/consensus/rounds/round_2/process/rescue/rescue_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for rescue_main function

- decentra_network/consensus/rounds/round_1/process/transactions/find_validated/find_validated_main.py
- decentra_network/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- decentra_network/consensus/rounds/round_2/process/process_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for round_process function of round 2

- decentra_network/consensus/rounds/round_2/round_2_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for consensus_round_2 function

- decentra_network/consensus/ongoing/ongoing_main.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for ongoing_main function

- decentra_network/consensus/consensus_main.py
- decentra_network/db/test_consensus_trigger_finished/README.md
- decentra_network/lib/clean_up.py
- tests/unit_tests/test_consensus.py
> tests: Added unit test for consensus_trigger function

- decentra_network/lib/mix/mixlib.py
- tests/unit_tests/test_lib.py
> tests: Added unit test for mixlib functions

- decentra_network/lib/status.py
- tests/unit_tests/test_lib.py
> tests: Added unit test for Status function

- .gitignore
- decentra_network/lib/export.py
- decentra_network/node/client/client.py
- tests/unit_tests/test_lib.py
> tests: Added unit test for export_the_transactions function

- decentra_network/lib/safety.py
- tests/unit_tests/test_lib.py
> tests: Added unit test for safety_check function

- decentra_network/api/main.py
- decentra_network/cli/main.py
- decentra_network/gui_lib/libs/baseclass/settings_screen.py
- decentra_network/lib/settings_system.py
- tests/unit_tests/test_lib.py
> tests: Added unit test for debug_mode function

- .gitignore
- tests/unit_tests/test_lib.py
> tests: Added unit test for perpetualTimer class

- tests/unit_tests/test_api.py
> tests: Added unit test for create_wallet_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for delete_wallets_page api

- decentra_network/api/main.py
- tests/unit_tests/test_api.py
> tests: Added unit test for send_coin_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for send_coin_data_page api

- decentra_network/accounts/get_accounts.py
- decentra_network/api/main.py
- tests/unit_tests/test_api.py
> tests: Added unit test for balance_wallets_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for node_start_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for node_stop_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for node_connect_page api

- decentra_network/api/main.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_api.py
> tests: Added unit test for node_connectmixdb_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for node_newunl_page api

- tests/unit_tests/test_api.py
> tests: Added unit test for node_id_page api

- tests/unit_tests/test_api.py
> tests: Adding unit test for settings_test_on_page api and settings_te… 

- tests/unit_tests/test_api.py
> tests: Added unit test for settings_debug_on_page api and settings_debug_off_page api

- decentra_network/api/main.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_api.py
> tests: Added unit test for block_get_page api

- decentra_network/api/main.py
- tests/unit_tests/test_api.py
> tests: Adding unit test for export_transaction_csv_page and export_transaction_json_page api

- decentra_network/api/main.py
- tests/unit_tests/test_api.py
> tests: Added unit test for status_page api

- .github/workflows/tests.yml
> github: Removed archiving logs for preventing errors from github

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> node: Added time to sending data for more security

- decentra_network/blockchain/block/hash/calculate_hash.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_node.py
> Some improvements for empty block numbers

- decentra_network/lib/cache.py
> lib: Added caching system basic

- decentra_network/accounts/get_accounts.py
- decentra_network/blockchain/block/blocks_hash.py
- decentra_network/blockchain/block/get_block.py
- decentra_network/blockchain/block/get_block_from_blockchain_db.py
- decentra_network/lib/cache.py
- decentra_network/lib/clean_up.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_lib.py
- tests/unit_tests/test_node.py
> lib: Added caching system

- docs/README.md
- docs/index.md
> docs: Changed Welcome to Introduction

- docs/concepts/index.md
- docs/getting-started/index.md
- docs/google_cloud_shell_tutorials/index.md
- docs/release-notes/index.md
> docs: Changed orders

- decentra_network/lib/status.py
> lib: Increased time.sleep of status function

- decentra_network/blockchain/block/get_block.py
- decentra_network/lib/status.py
> blockchain: Added no_cache option for GetBlock

- docs/release-notes/release-notes-0.26.1-alpha.md
- docs/release-notes/release-notes-0.27.0-alpha.md
- docs/release-notes/release-notes-0.27.1-alpha.md
- docs/release-notes/release-notes-0.28.0-alpha.md
- docs/release-notes/release-notes-0.29.0-alpha.md
> docs: Fixed Full Changelog section of release notes

- auto_builders/docker.py
- auto_builders/local.py
> auto_builders: Reduced wait times

- README.md
- docs/index.md
> docs: Changed tests are of today for Decentra Network

- docs/building_a_test_network/automatic.md
- docs/building_a_test_network/manuel.md
- docs/referances/apis.md
> docs: Changed `python` to `python3`

- decentra_network/transactions/check/len/check_len.py
- tests/unit_tests/test_transactions.py
> transactions: Improved checking len system with checking maximum amount and transaction fee

- decentra_network/transactions/check/check_transaction.py
- decentra_network/transactions/check/datas/check_datas.py
- decentra_network/transactions/check/len/check_len.py
- decentra_network/transactions/check/sign/check_sign.py
- decentra_network/transactions/check/type/check_type.py
> transactions: Changed checking logs for if not situations

- decentra_network/consensus/consensus_main.py
> consensus: Added garbage collection after consensus_trigger

- docs/creating_a_app/remote.md
> docs: Changed `/send` to `/send/`

- decentra_network/consensus/consensus_main.py
Reverts Decentra-Network/Decentra-Network#1099
> Revert "consensus: Added garbage collection after consensus_trigger"

- decentra_network/lib/perpetualtimer.py
- tests/unit_tests/test_lib.py
> lib: Some improvements for perpetualTimer

- docs/getting-started/installations/prerequisites.md
- docs/getting-started/tests/functional_tests.md
- docs/getting-started/tests/prerequisites.md
- docs/getting-started/tests/stability_tests.md
- docs/getting-started/tests/unit_tests.md
> Added test requirements

- decentra_network/api/main.py
- tests/unit_tests/test_api.py
> api: Added error logging

- decentra_network/accounts/save_accounts.py
- decentra_network/transactions/process_the_transaction.py
> accounts: Added multiple account saving in one time ability

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/blocks_hash.py
- decentra_network/blockchain/block/save_block.py
- decentra_network/blockchain/block/save_block_to_blockchain_db.py
- decentra_network/consensus/finished/finished_main.py
- decentra_network/lib/performance_analyzers/accounts.py
- decentra_network/lib/performance_analyzers/block.py
- decentra_network/lib/performance_analyzers/blockshash.py
- decentra_network/lib/performance_analyzers/blockshash_part.py
- decentra_network/lib/performance_analyzers/heartbeat_db.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_lib.py
- tests/unit_tests/test_node.py
> blockchain: Changed json based save system of blockshash list to sqllite

- decentra_network/blockchain/block/blocks_hash.py
- decentra_network/blockchain/block/save_block.py
- decentra_network/blockchain/block/save_block_to_blockchain_db.py
- decentra_network/lib/performance_analyzers/blockshash_part.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_consensus.py
- tests/unit_tests/test_node.py
> blockchain: Changed blockshash_part saving method with sqllite3

- auto_builders/docker.py
- auto_builders/local.py
- decentra_network/blockchain/block/block_main.py
- decentra_network/lib/performance_analyzers/heartbeat_db.py
- decentra_network/lib/status.py
- tests/functional_tests/docker/test_decentra_network_docker.py
- tests/functional_tests/local/test_decentra_network_local.py
- tests/stability_tests/docker/test_decentra_network_docker_10_3.py
- tests/stability_tests/docker/test_decentra_network_docker_3_1.py
- tests/stability_tests/docker/test_decentra_network_docker_4_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_1.py
- tests/stability_tests/docker/test_decentra_network_docker_5_2.py
- tests/stability_tests/docker/test_decentra_network_docker_6_1.py
- tests/stability_tests/docker/test_decentra_network_docker_6_2.py
- tests/stability_tests/docker/test_decentra_network_docker_7_1.py
- tests/stability_tests/docker/test_decentra_network_docker_7_2.py
- tests/stability_tests/local/test_decentra_network_local_10_3.py
- tests/stability_tests/local/test_decentra_network_local_3_1.py
- tests/stability_tests/local/test_decentra_network_local_4_1.py
- tests/stability_tests/local/test_decentra_network_local_5_1.py
- tests/stability_tests/local/test_decentra_network_local_5_2.py
- tests/stability_tests/local/test_decentra_network_local_6_1.py
- tests/stability_tests/local/test_decentra_network_local_6_2.py
- tests/stability_tests/local/test_decentra_network_local_7_1.py
- tests/stability_tests/local/test_decentra_network_local_7_2.py
> blockchain: Increased block time

- tests/unit_tests/test_lib.py
> tests: Set heartbeat get and save time to less than 9

- .github/workflows/deploys.yml
- setups/tests/setup.py
> packages: Added decentra_network_tests package

- setup.py
- setups/api/setup.py
- setups/gui/setup.py
- setups/remote_app/setup.py
- setups/tests/setup.py
> packages: Changed author email

- setups/api/setup.py
- setups/gui/setup.py
- setups/remote_app/setup.py
- setups/tests/setup.py
> packages: Changed url

- decentra_network/consensus/rounds/round_1/process/transactions/checks/duplicated.py
- decentra_network/consensus/rounds/round_1/process/transactions/transactions_main.py
- tests/unit_tests/test_consensus.py
> consensus: Removed duplicated transactions

- decentra_network/consensus/finished/transactions/transactions_main.py
- decentra_network/wallet/ellipticcurve/wallet_import.py
- docs/creating_a_app/embedded.md
- tests/unit_tests/test_consensus.py
- tests/unit_tests/test_wallet.py
> 708-wallet-getting-all-transaction-to-sendin-our-other-wallets

- decentra_network/api/main.py
- decentra_network/cli/main.py
- decentra_network/consensus/finished/transactions/transactions_main.py
- decentra_network/gui_lib/libs/baseclass/operations_screen.py
- decentra_network/transactions/my_transactions/get_my_transaction.py
- decentra_network/transactions/my_transactions/save_my_transaction.py
- decentra_network/transactions/my_transactions/save_to_my_transaction.py
- decentra_network/transactions/my_transactions/sended_transaction.py
- tests/unit_tests/test_consensus.py
- tests/unit_tests/test_transactions.py
> transactions: Seperated the sended or received transactions in my transactions

- docs/_includes/footer_custom.html
> docs: Fixed licence link

- LICENCE-decentra_network-gui_lib-libs-baseclass-tabnavigation.py__and__decentra_network-gui_lib-libs-kv-tabnavigation.kv
- decentra_network/gui_lib/libs/baseclass/tabnavigation.py
> licence: Changed licence for decentra_network-gui_lib-libs-baseclass-tabnavigation.py and decentra_network-gui_lib-libs-kv-tabnavigation.kv

- decentra_network/api/main.py
- decentra_network/transactions/my_transactions/get_my_transaction.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_transactions.py
> api: Added new /transactions/ based API's that seperated by sended or received and validated or not validated

- .github/workflows/codecov.yml
- .github/workflows/docker_stability_test_10_3.yml
- .github/workflows/docker_stability_test_3_1.yml
- .github/workflows/docker_stability_test_4_1.yml
- .github/workflows/docker_stability_test_5_1.yml
- .github/workflows/docker_stability_test_5_2.yml
- .github/workflows/docker_stability_test_6_1.yml
- .github/workflows/docker_stability_test_6_2.yml
- .github/workflows/docker_stability_test_7_1.yml
- .github/workflows/docker_stability_test_7_2.yml
- .github/workflows/local_stability_test_10_3.yml
- .github/workflows/local_stability_test_3_1.yml
- .github/workflows/local_stability_test_4_1.yml
- .github/workflows/local_stability_test_5_1.yml
- .github/workflows/local_stability_test_5_2.yml
- .github/workflows/local_stability_test_6_1.yml
- .github/workflows/local_stability_test_6_2.yml
- .github/workflows/local_stability_test_7_1.yml
- .github/workflows/local_stability_test_7_2.yml
- .github/workflows/tests.yml
> github: Changed environments

- docs/release-notes/release-notes-0.30.1-alpha.md
> docs: Fixed 0.30.1 full changelog link

- docs/referances/apis.md
> docs: Added new API docs

- .github/workflows/release.yml
> github: Added automatic release generator by pushing tag

- decentra_network/api/main.py
- docs/creating_a_app/remote.md
- docs/referances/apis.md
- tests/unit_tests/test_api.py
> api: Deprecated old incompatible `/export/transactions/json` API

- docs/creating_a_app/remote.md
Because some problems in here.
> docs: Some fixes for remote app document

- docs/creating_a_app/remote.md
> docs: Fixed building a test network link of remote app document

- decentra_network/consensus/rounds/round_1/checks/time/time_difference/time_difference_main.py
- decentra_network/consensus/rounds/round_2/checks/time/time_difference/time_difference_main.py
Because they are not true and need some cleaning.
> consensus: Fixed and cleaned round time calculators

- docs/_config.yml
> docs: Added website link

- docs/faq.md
> docs: Added Frequently Asked Questions

- requirements/tests.txt
- setups/tests/setup.py
Because it's needed for test_api.py tests.
> packages: Added decentra_network_api as an requirement to tests

- decentra_network/consensus/finished/finished_main.py
- tests/unit_tests/test_consensus.py
> blockchain: Changed blockchain db saving condition to transaction from us or to us

- decentra_network/consensus/finished/finished_main.py
- tests/unit_tests/test_consensus.py
> blockhain: Fixed all of part_amount system

- docs/concepts/apps.md
- docs/concepts/circulation.md
- docs/concepts/consensus.md
- docs/concepts/nodes.md
- docs/concepts/proofs.md
> docs: Added proofs docs

- docs/concepts/blockchain.md
> docs: Added docs for part_amount system

- decentra_network/cli/main.py
- decentra_network/transactions/my_transactions/get_proof.py
- docs/referances/clis.md
- tests/unit_tests/test_transactions.py
> cli: Added get and check proof ability to CLI

- decentra_network/api/main.py
- decentra_network/transactions/my_transactions/check_proof.py
- docs/referances/apis.md
- tests/unit_tests/test_api.py
- tests/unit_tests/test_transactions.py
> api: Added get and check proof of transaction ability

- decentra_network/api/main.py
> api: sys.path.append command moved to above of check and get proof imports

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/hash/blocks_hash.py
- decentra_network/consensus/finished/finished_main.py
- tests/unit_tests/test_blockchain.py
> blockchain: Added cache for calculation not effected blockshash part merkle tree

- decentra_network/lib/performance_analyzers/accounts.py
- decentra_network/lib/performance_analyzers/block.py
- decentra_network/lib/performance_analyzers/blockshash.py
- decentra_network/lib/performance_analyzers/blockshash_part.py
> lib: Added hash calculation to performance analyzers

- decentra_network/lib/performance_analyzers/block.py
- decentra_network/lib/performance_analyzers/heartbeat_db.py
- decentra_network/lib/performance_analyzers/transactions.py
> lib: Added transactions to performance analyzers

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/hash/calculate_hash.py
- decentra_network/consensus/finished/finished_main.py
- decentra_network/consensus/time/true_time/true_time_main.py
- decentra_network/lib/performance_analyzers/block.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_consensus.py
> blockchain: Increased block time for every part amount block for calculation new blockshash part merkle (Gap Blocks)

- decentra_network/blockchain/block/block_main.py
- decentra_network/consensus/finished/finished_main.py
- decentra_network/consensus/rounds/round_1/checks/time/time_difference/time_difference_main.py
- tests/unit_tests/test_consensus.py
> blockchain: Added a area for calculating long part list merkle root calculations (Hard Blocks)

- decentra_network/lib/performance_analyzers/heartbeat_db.py
- tests/unit_tests/test_lib.py
> lib: Seperating normal block and hard block performance analyzers

- decentra_network/transactions/pending_to_validating.py
- tests/unit_tests/test_transactions.py
> transactions: Added a ordering by transaction fee mechanism to pending to validating

- decentra_network/blockchain/block/block_main.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_consensus.py
> blockchain: Gap block number is fixed with + hard block number

- decentra_network/blockchain/block/block_main.py
- decentra_network/consensus/finished/finished_main.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_consensus.py
- tests/unit_tests/test_node.py
> blockchain: Added syncing with the network

- docs/concepts/blockchain.md
> docs: Added types of blocks

- docs/concepts/nodes.md
> docs: Added syncing docs

- README.md
- docs/index.md
> docs: Changed block time and added a note for some features

- decentra_network/accounts/get_balance.py
- decentra_network/transactions/check/datas/check_datas.py
- decentra_network/transactions/send.py
- tests/unit_tests/test_transactions.py
> accounts: Removed looking address and original argument balance together, added a argument for dont generate address for balance control of to user

- decentra_network/blockchain/block/block_main.py
> blockchain: Added new Green Paper hash to genesis block

- decentra_network/transactions/pending_to_validating.py
- tests/unit_tests/test_transactions.py
> transactions: Added logging to PendingtoValidating function

- decentra_network/node/server/server.py
> node: Added logging to server.check_connected function

- decentra_network/lib/log.py
> lib: Fixed multiple times same logging

- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> node: Added logging to server.run function

- decentra_network/blockchain/block/change_transaction_fee.py
> blockchain: Added logging to ChangeTransactionFee function

- decentra_network/consensus/rounds/round_1/checks/time/time_difference/time_difference_main.py
> consensus: Added logging to time control of round 1

- .github/restyled.yml
> github: Enabled resltyled pull request for forks based pull requests

- .github/restyled.yml
Reverts Decentra-Network/Decentra-Network#1259
> Revert "github: Enabled resltyled pull request for forks based pull requests"

- tests/unit_tests/test_node.py
I am sending this pr because currently system have a bug.
> tests: Fixed not unl node test

- decentra_network/consensus/rounds/round_1/process/transactions/checks/duplicated.py
> consensus: Added logging to remove duplicates of round 1

- decentra_network/consensus/rounds/round_2/process/process_main.py
> consensus: Added logging to process main of round 2

- decentra_network/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
> consensus: Added logging to process candidate block hashes of round 2

- decentra_network/consensus/rounds/round_1/process/transactions/find_validated/find_validated_main.py
> consensus: Added logging to find validated of round 1

- decentra_network/consensus/rounds/round_1/process/transactions/find_newly/find_newly_main.py
> consensus: Added logging to find newly of round 1

- decentra_network/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- decentra_network/consensus/rounds/round_2/process/rescue/rescue_main.py
> consensus: Added logging to rescue main of round 2

- decentra_network/consensus/rounds/round_1/process/process_main.py
> consensus: Added logging to process transaction of round 1

- decentra_network/consensus/finished/finished_main.py
- decentra_network/lib/performance_analyzers/blockshash.py
- decentra_network/lib/performance_analyzers/blockshash_part.py
> Removed unused cgitb reset function for fixing bugs on packages

- decentra_network/consensus/rounds/round_2/round_2_main.py
> consensus: Added logging to main of round 2

- decentra_network/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- decentra_network/consensus/rounds/round_2/checks/candidate_blocks_hashes/candidate_blocks_hashes_main.py
> consensus: Added logging to candidate block control of round 1

- decentra_network/consensus/rounds/round_1/checks/checks_main.py
- decentra_network/consensus/rounds/round_2/checks/checks_main.py
> consensus: Added logging to check main of round 1

- decentra_network/consensus/rounds/round_1/process/process_main.py
- decentra_network/consensus/rounds/round_2/process/process_main.py
> consensus: Added logging to process main of round 1

- decentra_network/consensus/rounds/round_1/round_1_main.py
> consensus: Added logging to  main of round 1

- decentra_network/gui_lib/libs/kv/node_screen.kv
- decentra_network/gui_lib/libs/kv/operations_screen.kv
- decentra_network/gui_lib/libs/kv/wallet_screen.kv
> gui: Fixed button text bug after updating requirements

- .github/workflows/builds.yml
> github: Removed caching from buildozer

- decentra_network/gui_lib/libs/baseclass/node_screen.py
- decentra_network/gui_lib/libs/kv/node_screen.kv
> gui: Added node id to QR code transformation

- decentra_network/gui_lib/libs/baseclass/wallet_screen.py
- decentra_network/gui_lib/libs/kv/wallet_screen.kv
> gui: Moved address copy to a button

- decentra_network/lib/notification.py
- decentra_network/transactions/my_transactions/save_to_my_transaction.py
- decentra_network/transactions/my_transactions/sended_transaction.py
- decentra_network/transactions/my_transactions/validate_transaction.py
- tests/unit_tests/test_lib.py
> transactions: Notification on validated and received and sended transaction

- .github/workflows/gource.yml
> github: Added gource action

- decentra_network/gui_lib/libs/baseclass/settings_screen.py
- decentra_network/gui_lib/libs/kv/settings_screen.kv
- decentra_network/lib/notification.py
- decentra_network/lib/settings_system.py
- tests/unit_tests/test_lib.py
> gui: Added mute notifications setting

- .gitignore
- decentra_network/config.py
- decentra_network/lib/backup/decentra_export.py
- decentra_network/lib/backup/decentra_import.py
- tests/unit_tests/test_lib.py
> lib: Added backup system

- README.md
> docs: Added supported OS to readme

- README.md
> docs: Added sponsors to readme

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/change_transaction_fee.py
- decentra_network/blockchain/block/shares.py
- decentra_network/consensus/ongoing/ongoing_main.py
- decentra_network/consensus/rounds/round_1/process/process_main.py
- decentra_network/consensus/rounds/round_1/round_1_main.py
- decentra_network/transactions/process_the_transaction.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_consensus.py
- tests/unit_tests/test_transactions.py
> blockchain: Added share mechanism of dnc

- decentra_network/blockchain/block/block_main.py
- tests/unit_tests/test_blockchain.py
Because the community green paper has been changed.
> blockchain: Changed community green paper hash

- decentra_network/lib/clean_up.py
> lib: Added cleaning test_app outputs

- decentra_network/cli/main.py
- decentra_network/lib/backup/decentra_export.py
- decentra_network/lib/backup/decentra_import.py
- tests/unit_tests/test_lib.py
> cli: Added backup system functions

- decentra_network/gui_lib/libs/baseclass/operations_screen.py
- decentra_network/gui_lib/libs/kv/operations_screen.kv
> gui: Added ability to send data

- decentra_network/lib/export.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_lib.py
> lib: Added sended variable to export transaction csv

- decentra_network/gui_lib/libs/baseclass/operations_screen.py
> gui: Fixed FileNotFoundError for GetBlock function usage

- decentra_network/gui_lib/libs/baseclass/node_screen.py
- decentra_network/gui_lib/libs/baseclass/operations_screen.py
> gui: Fixed NoneType errors that caused by server.Server

- setup.py
> packages: Fixed console script bug by adding .main before using start function

- README.md
> docs: Removed lgtm from readme

- README.md
> docs: Fixed codacy badge on readme

- decentra_network/api/main.py
- docs/referances/apis.md
- tests/unit_tests/test_api.py
> api: Added api for gathering the block as json

- docs/concepts/accounts.md
- docs/concepts/apps.md
- docs/concepts/architecture.md
- docs/concepts/blockchain.md
- docs/concepts/circulation.md
- docs/concepts/consensus.md
- docs/concepts/nodes.md
- docs/concepts/proofs.md
- docs/concepts/transactions.md
- docs/concepts/user_interfaces.md
> docs: Added user interfaces to concepts

- docs/getting-started/usages.md
> docs: Added usage docs to getting started

- docs/faq.md
- docs/videos.md
> docs: Added Videos index

- decentra_network/node/server/server.py
> node: Added socket.timeout suppress for send_client function

- decentra_network/consensus/rounds/round_1/process/transactions/find_validated/find_validated_main.py
> consensus: Added the self to round 1 find validated transactions voting

- decentra_network/lib/perpetualtimer.py
> lib: Added suppress to perpetualtimer

- decentra_network/blockchain/block/block_main.py
- docs/concepts/circulation.md
> consensus: Increased circulation time to 1.50s

- decentra_network/blockchain/block/hash/calculate_hash.py
- tests/unit_tests/test_blockchain.py
> blockchain: Removed empty block number from hash calculation

- decentra_network/consensus/rounds/round_1/round_1_main.py
- decentra_network/consensus/rounds/round_2/round_2_main.py
> consensus: Moved candidate block sending to the start of rounds

- decentra_network/consensus/consensus_main.py
- decentra_network/consensus/rounds/round_1/round_1_main.py
- decentra_network/consensus/rounds/round_2/round_2_main.py
> consensus: Moved candidate block sending to the start of consensus_main

- decentra_network/transactions/process_the_transaction.py
> transactions: Added cleaning signature == "DN" transactions before share transactions

- decentra_network/consensus/consensus_main.py
- decentra_network/consensus/rounds/round_1/round_1_main.py
- decentra_network/consensus/rounds/round_2/round_2_main.py
> consensus: Reverted cadidate block sending

- decentra_network/blockchain/block/block_main.py
- docs/concepts/circulation.md
> consensus: Increased circulation time to 2s

- decentra_network/blockchain/block/save_block.py
> blockchain: Added double saving for SaveBlock

- decentra_network/consensus/consensus_main.py
- decentra_network/consensus/rounds/round_1/round_1_main.py
- decentra_network/consensus/rounds/round_2/round_2_main.py
Reverts Decentra-Network/Decentra-Network#1377
> Revert "consensus: Reverted cadidate block sending"

- decentra_network/blockchain/block/block_main.py
> blockchain: Removed candidate block resetting

- decentra_network/blockchain/block/block_main.py
Reverts Decentra-Network/Decentra-Network#1387
> Revert "blockchain: Removed candidate block resetting"

- decentra_network/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- decentra_network/consensus/rounds/round_2/checks/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- decentra_network/node/get_candidate_blocks.py
- decentra_network/node/server/server.py
> consensus: Added self adding to canddiate block checks

- decentra_network/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- decentra_network/consensus/rounds/round_2/checks/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- docs/concepts/consensus.md
- tests/unit_tests/test_consensus.py
> consensus: All systems assigned to majority

- decentra_network/node/client/client.py
- decentra_network/node/get_candidate_blocks.py
- decentra_network/node/server/server.py
- tests/unit_tests/test_node.py
> node: Stored last 5 candidate blocks and getting by sequance number

- docs/getting-started/installations/downloads.md
> docs: Removed gui macos from installations

- decentra_network/blockchain/block/block_main.py
- decentra_network/blockchain/block/hash/calculate_hash.py
- decentra_network/consensus/consensus_main.py
> blockchain: Added transaction fee based values to calculating hash

- decentra_network/gui/main.py
- decentra_network/gui_lib/libs/baseclass/settings_screen.py
- decentra_network/gui_lib/libs/kv/node_screen.kv
- decentra_network/gui_lib/libs/kv/operations_screen.kv
- decentra_network/gui_lib/libs/kv/root_screen.kv
- decentra_network/gui_lib/libs/kv/settings_screen.kv
- decentra_network/gui_lib/libs/kv/wallet_screen.kv
- decentra_network/gui_lib/libs/kv/welcome_screen.kv
- decentra_network/lib/settings_system.py
- tests/unit_tests/test_lib.py
> gui: Added a switch for dark mode or light mode

- tests/unit_tests/test_consensus.py
> tests: Fixed test_finished_main_save_from_no_part test

- tests/unit_tests/test_blockchain.py
> tests: Fixed test_block_reset_start_time_none

- docs/concepts/apps.md
> docs: Changed apps concept data name to data_1 and data_2

- docs/concepts/apps.md
> docs: Seperating Apps concept to Decentra Networks

- decentra_network/lib/settings_system.py
> gui: Changed default theme to light

- decentra_network/lib/verify.py
> wallet: Added check exported signed file function

- decentra_network/cli/main.py
> cli: Added ability to sign and verify data in menu

- decentra_network/cli/main.py
> cli: Added after a key press clearing screen for menu

- decentra_network/api/main.py
- decentra_network/lib/sign.py
- docs/referances/apis.md
- tests/unit_tests/test_api.py
> api: Added ability to sign and verify data

- decentra_network/gui_lib/libs/baseclass/operations_screen.py
- decentra_network/gui_lib/libs/kv/operations_screen.kv
> gui: Added ability to sign and verify data

- auto_builders/docker.py
- auto_builders/local.py
> auto_builders: Made networks with more connected circles

- decentra_network/transactions/cleaner.py
- decentra_network/transactions/pending_to_validating.py
- tests/unit_tests/test_transactions.py
> transactions: Adding a cleaner for preventing leaks

- decentra_network/node/server/server.py
> node: Added a control point for dont sending system transactions to other node

- decentra_network/consensus/finished/finished_main.py
> consensus: Moved the hard block wait to end of calculation

- decentra_network/blockchain/block/block_main.py
- tests/unit_tests/test_blockchain.py
> block: Removed start_time edits for gap blocks in sync

- decentra_network/gui_lib/libs/baseclass/operations_screen.py
> gui: Added copy transaction signature from transaction history section

- decentra_network/gui/main.py
- decentra_network/gui_lib/libs/baseclass/node_screen.py
- decentra_network/gui_lib/libs/baseclass/operations_screen.py
- decentra_network/gui_lib/libs/baseclass/wallet_screen.py
> gui: Added using global font_path from App

- decentra_network/gui/main.py
- decentra_network/gui/popup.py
- decentra_network/gui_lib/libs/baseclass/root_screen.py
- decentra_network/gui_lib/libs/kv/root_screen.kv
> gui: Removed title bar and added close button to navbar with popup

- buildozer.spec
> gui: Added custom splash screen

- setup.py
- setups/api/setup.py
- setups/gui/setup.py
- setups/remote_app/setup.py
- setups/tests/setup.py
I am sending this pr because the mail is changed.
> packages: Changed the author_email

- naruno/lib/settings_system.py
- tests/unit_tests/test_lib.py
> lib: Added publisher mode setting

- naruno/cli/main.py
> cli: Added publisher mode changer to menu and arguments

- README.md
> docs: Fixed image links

- naruno/api/main.py
> api: Added a api for gettng sequance number of specific user

- naruno/api/main.py
> api: Added get sequence number of an user

- docs/getting-started/usages.md
> docs: Added wallet creating document in usages

- naruno/blockchain/block/save_block.py
- naruno/lib/settings_system.py
> blockchain: Added baklava testnet users

- naruno/blockchain/block/hash/accounts_hash.py
> blockchain: Fixed accounts list hash calculation

- naruno/apps/remote_app.py
> apps: Added multiple account support

- naruno/lib/backup/naruno_import.py
- naruno/lib/settings_system.py
Because there is an problem for backups.
> lib: Added backward support for settings

- docs/building_a_test_network/manuel.md
> docs: Fixed buiding testnetwork manuel typo

- README.md
- auto_builders/docker.py
- auto_builders/local.py
- docs/index.md
- naruno/api/main.py
- naruno/cli/main.py
- naruno/gui/main.py
- setup.py
> docs: Fixed introducing typos

- docs/baklavatestnet/index.md
- docs/baklavatestnet/using.md
- docs/concepts/index.md
- docs/faq.md
- docs/referances/index.md
- docs/release-notes/index.md
- docs/videos.md
Because its pubished, and waited from someones.
> docs: Added baklava testnet document

- .github/workflows/docs_videos.yml
- docs/videos.md
- docs/videos/baklavatestnet.py
- docs/videos/main.py
> docs: Added baklava testnet video

- naruno/accounts/get_balance.py
- naruno/blockchain/block/get_minumum_transfer_amount.py
> accounts: Added support for getting balance from baklava testnet

- naruno/cli/main.py
> cli: Fixed getbalance function printing result

- docs/getting-started/usages.md
> docs: Removed pip install section from wallet creation doc

- docs/baklava-testnet.md
> docs: Added upgrading section to baklava testnet document

- docs/baklava-testnet.md
> docs: Removed wallet creation section from baklava testnet

- naruno/apps/remote_app.py
> apps: Fixed apps caching mechanism the cache key changed with transaction signature

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Added backward suport for old caches

- naruno/transactions/my_transactions/save_to_my_transaction.py
> transactions: Removed system transactions saving

- docs/baklava-testnet.md
> docs: Added a section for downloading naruno-remote-app library

- setups/remote_app/setup.py
- setups/tests/setup.py
> packages: Upgraded requests library version

- naruno/apps/remote_app.py
> apps: Added some loggers for remote app integration class

- naruno/lib/notification.py
> lib: Removed useless loggers from notification system

- naruno/apps/remote_app.py
> apps: Added automatic address transformation for fromUser

- docs/baklava-testnet.md
- docs/creating_a_app/remote.md
- docs/getting-started/tests/prerequisites.md
> docs: Changed upgrading with --upgrade function

- naruno/blockchain/block/save_block.py
- naruno/lib/settings_system.py
> blockchain: Changed saveblock baklava settings with another settings for preventing baklava mode loop problem caused from getting balance

- docs/baklava-testnet.md
- naruno/api/main.py
- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Added automatic api start

- naruno/api/main.py
> api: Changed request loggers to debug logs

- docs/baklava-testnet.md
> docs: Added a section for running the Web3_App.py in baklava testnet document

- naruno/apps/remote_app.py
> apps: Added send forcer system for multiple sending in same times. (tx sequencer)

- naruno/api/main.py
- naruno/apps/remote_app.py
- naruno/blockchain/block/max_data_size.py
- naruno/blockchain/block/max_tx_number.py
> apps: Added automatic splitting for big datas

- naruno/apps/remote_app.py
> apps: Added contextlib suppress for preventing errors that caused from inspect module

- naruno/lib/backup/naruno_import.py
For fixing backup and import between different installation
> lib: Added safe main folder system for backup importing

- naruno/lib/settings_system.py
> lib: Added a settings repair tools missing settings

- tests/unit_tests/test_apps.py
- tests/unit_tests/test_consensus.py
> tests: Fixed unit tests

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Fixed getting sended and sended_not_validated for baklava testnet

- docs/baklava-testnet.md
- docs/creating_a_app/remote.md
- naruno/apps/remote_app.py
> apps: Added amount sending feature in remote app integration

- docs/getting-started/usages.md
> docs: Added installation information to wallet creating document

- naruno/transactions/process_the_transaction.py
> transactions: Fixed self-posting transactions

- auto_builders/docker.py
- auto_builders/local.py
> auto_builders: Reduced time sleep after installation

- naruno/blockchain/block/block_main.py
> blockchain: Max tx number increased

- naruno/blockchain/block/save_block_to_blockchain_db.py
- naruno/lib/settings_system.py
> blockchain: Added a feature for disabling block saving

- naruno/node/client/client.py
> node: Added bypass exception fr deleting buffer of data for enough data size situations

- naruno/apps/remote_app.py
> apps: Added fault tolerance for big datas

- naruno/apps/remote_app.py
> apps: Added a wait system between sends

- naruno/apps/remote_app.py
For preventing sometimes errors.
> apps: Optimized max_data_size and max_tx_number gathering system

- naruno/apps/remote_app.py
> apps: Fixed max_data_size and max_tx_number gathering

- naruno/apps/remote_app.py
> apps: Bad split bug fixed

- naruno/apps/remote_app.py
> apps: Fixed custom wait time setting

- naruno/apps/remote_app.py
> apps: Added checker system for preventing not validated transactions

- naruno/apps/remote_app.py
> apps: Fixed a many call problem that caused by broken splits

- naruno/apps/remote_app.py
> apps: Fixed a bug about false calls caused by broken splits

- naruno/apps/remote_app.py
> apps: Fixed checker system bug that caused by another get call

- naruno/apps/remote_app.py
> apps: Changed checking order in splits for preventing uncomplated splits

- naruno/apps/remote_app.py
> apps: Fixed vaue error bug

- naruno/apps/remote_app.py
> apps: Cache operations are disabled for checker for preventing leaks in multiple threads

- naruno/blockchain/block/block_main.py
> blockchain: Increased transaction delay to a suitable value for preventing missed transactions

- naruno/apps/remote_app.py
> apps: Fixed value error bug for sended_txs list

- naruno/apps/remote_app.py
> apps: Fixed multithreading bug for host and port

- naruno/apps/remote_app.py
> apps: Fixed get_all parameter and cache relationship for checker multithreading bug

- naruno/node/get_candidate_blocks.py
- naruno/node/server/server.py
> node: Added empty block number for making a timeout

- naruno/node/server/server.py
> node: Added a control point for candidate blocks values

- naruno/node/get_candidate_blocks.py
- naruno/node/server/server.py
> Revert "node: Added empty block number for making a timeout"

- naruno/node/server/server.py
> node: Made seperated sending for candidate block txs

- naruno/node/server/server.py
> node: Connected buffer size to max_data_size and max_tx_number

- naruno/node/client/client.py
- naruno/node/server/server.py
> node: Added minumum buffer size for preventing errors that caused by bad configs

- setups/remote_app/setup.py
> packages: Added naruno_api as an requirement to naruno_remote_app

- naruno/apps/remote_app.py
> apps: Added commander support

- README.md
> docs: Codebeat badges fixed

- naruno/blockchain/block/block_main.py
- naruno/blockchain/block/hash/calculate_hash.py
- naruno/transactions/check/datas/check_datas.py
- tests/unit_tests/test_blockchain.py
> blockchain: Added disabling just one transaction from same addresses

- naruno/apps/remote_app.py
> apps: Added ability to sending multiple tx to same blockchain

- naruno/apps/remote_app.py
> apps: Added a section for checking last max_tx_number/2 transactions

- naruno/api/main.py
- naruno/blockchain/block/just_one_tx.py
> api: Added /blockjustonetx get api

- naruno/api/main.py
- naruno/apps/remote_app.py
> apps: Sequance number calculation moved to api

- tests/unit_tests/test_apps.py
> tests: Fixed apps unit tests

- naruno/apps/remote_app.py
> apps: Fixed sended not validated txs in get function

- naruno/blockchain/block/block_main.py
> blockchain: Max tx number increased to 1000

- naruno/blockchain/block/block_main.py
> blockchain: Round 1 time increased and round 2 time is decreased

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> tests: Added automatic start and closing without api unit tests for apps

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> Revert "tests: Added automatic start and closing without api unit tests for apps"

- naruno/blockchain/block/block_main.py
> blockchain: Block time increased to 27 second

- naruno/lib/performance_analyzers/block.py
> blockchain: Added data for block performance calculation

- auto_builders/docker.py
- auto_builders/local.py
- naruno/api/main.py
- naruno/blockchain/block/block_main.py
- naruno/lib/settings_system.py
> tests: Fixed the functional test with custom set max_data_size and max_tx_number with funtionaltest_mode

- naruno/lib/settings_system.py
- naruno/lib/status.py
- tests/unit_tests/test_api.py
- tests/unit_tests/test_lib.py
> lib: Added caching for status

- naruno/lib/settings_system.py
- naruno/lib/status.py
> lib: Added a system for preventing the multiple status call

- naruno/lib/status.py
- tests/unit_tests/test_lib.py
> lib: Added a fix system for broken status procces

- auto_builders/docker.py
- auto_builders/local.py
- tests/functional_tests/docker/test_naruno_docker.py
- tests/functional_tests/local/test_naruno_local.py
- tests/stability_tests/docker/test_naruno_docker_10_3.py
- tests/stability_tests/docker/test_naruno_docker_3_1.py
- tests/stability_tests/docker/test_naruno_docker_4_1.py
- tests/stability_tests/docker/test_naruno_docker_5_1.py
- tests/stability_tests/docker/test_naruno_docker_5_2.py
- tests/stability_tests/docker/test_naruno_docker_6_1.py
- tests/stability_tests/docker/test_naruno_docker_6_2.py
- tests/stability_tests/docker/test_naruno_docker_7_1.py
- tests/stability_tests/docker/test_naruno_docker_7_2.py
- tests/stability_tests/local/test_naruno_local_10_3.py
- tests/stability_tests/local/test_naruno_local_3_1.py
- tests/stability_tests/local/test_naruno_local_4_1.py
- tests/stability_tests/local/test_naruno_local_5_1.py
- tests/stability_tests/local/test_naruno_local_5_2.py
- tests/stability_tests/local/test_naruno_local_6_1.py
- tests/stability_tests/local/test_naruno_local_6_2.py
- tests/stability_tests/local/test_naruno_local_7_1.py
- tests/stability_tests/local/test_naruno_local_7_2.py
> auto_builders: Fixed test mode bug with test_mode parameter

- naruno/apps/remote_app.py
- naruno/transactions/my_transactions/get_my_transaction.py
> apps: Added rezistance for broken transactions that caused by network activity

- tests/unit_tests/test_api.py
- tests/unit_tests/test_lib.py
> tests: Fixed api and lib unit tests

- naruno/api/main.py
> api: Fixed send function in network uses with moving try except

- naruno/apps/remote_app.py
> apps: Added initialize the API for stopped paralel Apps

- naruno/lib/status.py
> lib: Fixed json syntax error in status transactions_of_us element

- naruno/apps/remote_app.py
> apps: Added fault tolerance for raw datas

- naruno/lib/log.py
> lib: Added colors to logs streamline

- naruno/lib/log.py
> lib: Added filename and linenumber to logging format

- naruno/lib/log.py
> lib: Fixed colored logs for win32

- naruno/lib/log.py
- tests/unit_tests/test_lib.py
> lib: Added log cleaner

- naruno/blockchain/block/block_main.py
> blockchain: Added automatic log cleaning for block number changes

- naruno/lib/log.py
- naruno/lib/settings_system.py
> lib: Added a setting for disabling log cleaning

- naruno/blockchain/block/block_main.py
> blockchain: Added use_full_block element for block for filled controlling

- naruno/apps/checker.py
- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Checker function logged, added tests and explained

- naruno/lib/log.py
> lib: Fixed clear_logs for win32

- tests/unit_tests/test_lib.py
> tests: Fixed log tests for windows

- naruno/apps/remote_app.py
> apps: Fixed checker thread

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> tests: Added test for Integration.send_forcer function

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> tests: Added unit tests for Integration splited send system

- naruno/lib/backup/naruno_export.py
- naruno/lib/backup/naruno_import.py
> licence: Added licence to naruno import and export libraries

- tests/unit_tests/test_blockchain.py
> tests: Fixed test_blockchain_sync_empty_blocks_first_and_second_empty_is_equal

- naruno/node/client/client.py
- naruno/node/server/server.py
> node: All loggings are redesigned

- naruno/lib/config_system.py
- naruno/lib/settings_system.py
- naruno/node/unl.py
- naruno/wallet/get_saved_wallet.py
- naruno/wallet/save_wallet_list.py
- naruno/wallet/wallet_create.py
- naruno/wallet/wallet_delete.py
- naruno/wallet/wallet_import.py
> Removed the `import *`

- naruno/lib/safety.py
> lib: Redesigned safety logs

- naruno/api/main.py
> api: Redesigned info logs

- naruno/transactions/send.py
> transactions: send function loggers redesigned

- naruno/blockchain/block/get_block.py
> blockchain: get_block function logger.info's redesigned

- naruno/api/main.py
> api: 404 loggers changed with logger.debug

- naruno/lib/log.py
> lib: Changed log format for more readeble logs

- .github/workflows/builds.yml
- buildozer.spec
- recipes/src/python-for-android/recipes/naruno/__init__.py
> Fixed the buildozer builds

- .github/workflows/builds.yml
- buildozer.spec
- recipes/src/python-for-android/recipes/naruno/__init__.py
> github: Fixed buildozer builds

- .github/workflows/builds.yml
> github: Added cache for buildozer builds

- naruno/gui/main.py
> gui: Fixed mobile input empty bug

- buildozer.spec
> packages: Made full screen the gui on mobile

- SECURITY.md
> github: Changed security policy mail

- naruno/blockchain/block/shares.py
- tests/unit_tests/test_blockchain.py
- tests/unit_tests/test_transactions.py
> blockchain: Added different start times for shares

- README.md
- docs/index.md
> docs: Added contributors to readme

- naruno/blockchain/block/shares.py
> blockchain: Added docstring for shares

- naruno/cli/main.py
> cli: Added sign function to CLI argument

- naruno/cli/main.py
> cli: Added verify function to CLI argument

- naruno/gui/lib/libs/baseclass/operations_screen.py
- naruno/lib/sign.py
- tests/unit_tests/test_lib.py
> lib: Changed "None" return to "Password is not true"

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> tests: Added some unit tests for Integration class

- naruno/gui/lib/libs/kv/settings_screen.kv
> gui: Fixed layout of settings page

- .gitignore
- naruno/lib/settings_system.py
> lib: Moved settings save&get to KOT

- naruno/accounts/commanders/delete_commander.py
- naruno/accounts/commanders/get_comnder.py
- naruno/accounts/commanders/save_commander.py
> accounts: Moved commander save&get to KOT

- naruno/transactions/my_transactions/get_my_transaction.py
- naruno/transactions/my_transactions/save_my_transaction.py
> transactions: Moved my transaction save&get to KOT

- naruno/lib/kot.py
- naruno/transactions/pending/delete_pending.py
- naruno/transactions/pending/get_pending.py
- naruno/transactions/pending/save_pending.py
> transactions: Moved pending transaction save&get to

- naruno/lib/config_system.py
> lib: Moved config save&get to KOT

- naruno/node/unl.py
> node: Moved unl save&get to KOT

- naruno/node/server/server.py
> node: Moved connected node save&get to KOT

- naruno/wallet/get_saved_wallet.py
- naruno/wallet/save_wallet_list.py
- naruno/wallet/wallet_delete.py
> wallet: Moved wallet save&get to KOT

- tests/unit_tests/test_lib.py
> tests: Moving test api perpetual time tester function save&get to KOT

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Moved cache save&get to KOT

- naruno/blockchain/block/blocks_hash.py
- naruno/lib/kot.py
> blockchain: Moved blockshash save&get to KOT

- naruno/accounts/get_balance.py
- naruno/blockchain/block/get_block.py
- naruno/blockchain/block/get_block_from_blockchain_db.py
- naruno/blockchain/block/get_minumum_transfer_amount.py
- naruno/blockchain/block/save_block.py
- naruno/gui/lib/libs/baseclass/operations_screen.py
- naruno/transactions/my_transactions/get_proof.py
> blockchain: Moving block save&get to KOT

- naruno/gui/lib/libs/baseclass/settings_screen.py
- naruno/gui/lib/libs/kv/settings_screen.kv
> gui: Added baklava setting

- naruno/gui/popup.py
> gui: Changed box layout to grid layout for popups

- naruno/transactions/my_transactions/get_my_transaction.py
> transactions: Added syncing feature for tx validation for baklava network users

- naruno/gui/lib/libs/baseclass/operations_screen.py
> gui: Fixed signature copy of get my transaction section

- naruno/gui/lib/libs/baseclass/operations_screen.py
- naruno/gui/lib/libs/kv/operations_screen.kv
> gui: Fixed amount situations and data info on send

- naruno/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- naruno/consensus/rounds/round_1/process/transactions/find_validated/find_validated_main.py
> consensus: Changed required valid with 80 of round 1

- naruno/consensus/rounds/round_2/checks/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- naruno/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
> consensus: Changed required valid with 80 of round 2

- naruno/lib/kot.py
> lib: Updated KOT

- naruno/node/get_candidate_blocks.py
> node: Added last_control mechanism and dedicated variables to self_candidates for fixing a bug

- docs/_config.yml
> docs: Fixed Google Analytics tracking code

- naruno/apps/remote_app.py
> apps: Some time adjustment made for more stable Integration

- naruno/apps/remote_app.py
> apps: Some value adjustment made for more stable Integration

- naruno/api/main.py
> api: Fixed /balance/get/ and /sequence/get/ endpoint block gathering ways

- naruno/apps/remote_app.py
> apps: Fixed send_splitter resend bug

- docs/baklava-testnet/baklava-testnet.md
- docs/baklava-testnet/index.md
- docs/baklava-testnet/ovenden-incentive.md
- docs/baklava-testnet/scan.md
> docs: Added Ovenden Incentive and Baklava Scan Page and made some fixes for Baklava TestNet documents

- docs/getting-started/usages.md
> docs: Added a section for wallet creating about switching new wallet

- naruno/cli/main.py
> cli: Fixed sending with baklava

- tests/unit_tests/test_node.py
> tests: Fixed test_GetCandidateBlocks_different_squance_number

- naruno/apps/remote_app.py
> apps: Fixed TypeError bug

- tests/unit_tests/test_node.py
https://github.com/Naruno/Naruno/actions/runs/5740554576/job/15558817625
> tests: Fixed test_send_my_block_get_candidate_block_multiple_with_function_try

- naruno/lib/settings_system.py
> lib: Removed debug mode activating in the start bug

- naruno/cli/main.py
> cli: Moved safety check to top

- naruno/lib/safety.py
> lib: Changed checking safety logger to debug

- naruno/accounts/get_balance.py
> accounts: Fixed false balance problem from currently block included calculations

- naruno/accounts/save_accounts.py
- naruno/blockchain/block/change_transaction_fee.py
- naruno/blockchain/block/save_block.py
- naruno/blockchain/block/save_block_to_blockchain_db.py
- naruno/consensus/consensus_main.py
- naruno/consensus/finished/finished_main.py
- naruno/consensus/finished/true_time/true_time_main.py
- naruno/consensus/rounds/round_1/checks/candidate_blocks/candidate_blocks_main.py
- naruno/consensus/rounds/round_1/checks/time/time_difference/time_difference_main.py
- naruno/consensus/rounds/round_1/process/process_main.py
- naruno/consensus/rounds/round_1/process/transactions/checks/duplicated.py
- naruno/consensus/rounds/round_1/process/transactions/find_newly/find_newly_main.py
- naruno/consensus/rounds/round_2/checks/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- naruno/consensus/rounds/round_2/checks/time/time_difference/time_difference_main.py
- naruno/consensus/rounds/round_2/process/candidate_blocks_hashes/candidate_blocks_hashes_main.py
- naruno/transactions/my_transactions/validate_transaction.py
- naruno/transactions/pending_to_validating.py
- naruno/transactions/process_the_transaction.py
> Loggers improved

- naruno/apps/remote_app.py
> apps: Removed backward support for cache for preventing bug

- naruno/apps/remote_app.py
> apps: Moved new data log to main get function from _get function

- naruno/apps/remote_app.py
- tests/unit_tests/test_apps.py
> apps: Removed app name from action in Integration

- naruno/apps/remote_app.py
> apps: Added transaction signature to message sent log in the Integration

- naruno/transactions/my_transactions/get_my_transaction.py
> transactions: Background processor disabled

- naruno/apps/checker.py
> apps: Fixed app_name bug in checker

- tests/unit_tests/test_apps.py
> tests: Fixed test_checker_with_valid_transactions
